//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCT : IEquatable<FCT>
    {
        public int NMatricula { get; set; }
        public int IdEmpresa { get; set; }
        public string TutorInsti { get; set; }
        public string TutorEmpresa { get; set; }

        public FCT(int nMatricula, int idEmpresa, string tutorInsti, string tutorEmpresa)
        {
            NMatricula = nMatricula;
            IdEmpresa = idEmpresa;
            TutorInsti = tutorInsti;
            TutorEmpresa = tutorEmpresa;
        }

        public FCT()
        {
        }

        public virtual Alumno Alumno { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Profe Profe { get; set; }

        public override bool Equals(object obj)
        {
            return Equals(obj as FCT);
        }

        public bool Equals(FCT other)
        {
            return other != null &&
                   NMatricula == other.NMatricula &&
                   IdEmpresa == other.IdEmpresa &&
                   TutorInsti.ToLower() == other.TutorInsti.ToLower() &&
                   TutorEmpresa.ToLower() == other.TutorEmpresa.ToLower();
        }

        public override int GetHashCode()
        {
            int hashCode = -1671427016;
            hashCode = hashCode * -1521134295 + NMatricula.GetHashCode();
            hashCode = hashCode * -1521134295 + IdEmpresa.GetHashCode();
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(TutorInsti);
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(TutorEmpresa);
            return hashCode;
        }
    }
}
